config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cars
  resources :alunos
  get 'demo/index'
  get 'demo/listagem'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aluno.rb
class Aluno < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.all
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :telefone, :matricula, :ira)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:modelo, :ano, :cor)
    end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  def index
  end

  def listagem
  end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/views/alunos/_form.html.erb
<%= form_with(model: aluno, local: true) do |form| %>
  <% if aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :matricula %>
    <%= form.number_field :matricula %>
  </div>

  <div class="field">
    <%= form.label :ira %>
    <%= form.text_field :ira %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Matricula</th>
      <th>Ira</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.telefone %></td>
        <td><%= aluno.matricula %></td>
        <td><%= aluno.ira %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form', aluno: @aluno %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @aluno.telefone %>
</p>

<p>
  <strong>Matricula:</strong>
  <%= @aluno.matricula %>
</p>

<p>
  <strong>Ira:</strong>
  <%= @aluno.ira %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano %>
  </div>

  <div class="field">
    <%= form.label :cor %>
    <%= form.text_field :cor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Ano</th>
      <th>Cor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.modelo link_to car.modelo, edit_car_path(car) %></td>
        <td><%= car.ano %></td>
        <td><%= car.cor %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @car.modelo %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @car.ano %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @car.cor %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/demo/index.html.erb
<h1>Demo#index 123 456</h1>
<p>Find me in app/views/demo/index.html.erb</p>

<% a = 1 %>
<% b = 2 %>
<% c = a + b %>
<%= c %>

app/views/demo/listagem.html.erb
<h1>Demo#listagem</h1>
<p>Find me in app/views/demo/listagem.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ep3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>